name: comics_app
description: Marvel comics catalog.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  convert: ^3.1.1
  crypto: ^3.0.3
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_card_swiper: ^6.0.0
  flutter_dotenv: ^5.1.0
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
